openapi: 3.0.0
info:
  title: hello-api
  version: 1.0.0
paths:
  /hello:
    get:
      description: Hello world
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
      security:
      - MockAuthorizer: []
      - ApiKey: []
      x-amazon-apigateway-integration:
        uri: '$LAMBDA_HELLO_HANDLER$'
        payloadFormatVersion: '2.0'
        httpMethod: 'POST'
        passthroughBehavior: 'when_no_match'
        type: 'aws_proxy'
components:
  securitySchemes:
    MockAuthorizer:
      type: 'apiKey'
      name: 'Authorization'
      in: 'header'
      x-amazon-apigateway-authtype: 'custom'
      x-amazon-apigateway-authorizer:
        authorizerUri: '$LAMBDA_MOCK_AUTHORIZER$'
        authorizerResultTtlInSeconds: 30
        type: 'token'
    ApiKey:
      type: 'apiKey'
      name: 'x-api-key'
      in: 'header'
      x-amazon-apigateway-api-key-source: 'HEADER'
